# Generated by Django 2.1.4 on 2019-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190418_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
