# Generated by Django 2.1.4 on 2019-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190420_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='img',
            field=models.ImageField(upload_to='media/foto/'),
        ),
    ]
