# Generated by Django 2.2.4 on 2019-09-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190907_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
