# Generated by Django 2.2.4 on 2019-09-08 16:40

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_book_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 16, 40, 27, 887666, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
