# Generated by Django 2.2.4 on 2019-09-08 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20190908_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=datetime.datetime(2019, 9, 8, 16, 58, 24, 514587, tzinfo=utc), upload_to='covers_book/'),
            preserve_default=False,
        ),
    ]
