# Generated by Django 2.2.4 on 2019-09-09 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 16, 59, 37, 295319, tzinfo=utc), editable=False),
        ),
    ]
