# Generated by Django 2.2.4 on 2019-09-12 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190909_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='read_can',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='title',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers_book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 18, 53, 4, 191359, tzinfo=utc), editable=False),
        ),
    ]
