# Generated by Django 2.2.4 on 2019-09-16 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190912_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='title_read',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 6, 32, 3, 933261, tzinfo=utc), editable=False),
        ),
    ]
