# Generated by Django 2.2.4 on 2019-09-20 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190916_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='table_of_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 17, 24, 46, 252188, tzinfo=utc), editable=False),
        ),
    ]
