# Generated by Django 2.2.4 on 2019-10-05 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20190924_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 18, 3, 16, 424838, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_chapter', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('book_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BookRead')),
            ],
        ),
        migrations.AddField(
            model_name='bookread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book'),
        ),
    ]
