# Generated by Django 2.2.4 on 2019-10-05 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20191005_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfile',
            name='read_can',
        ),
        migrations.RemoveField(
            model_name='bookfile',
            name='table_of_content',
        ),
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 18, 43, 28, 86841, tzinfo=utc), editable=False),
        ),
    ]
