# Generated by Django 2.2.4 on 2019-10-05 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20191006_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='visit_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 19, 37, 27, 179792, tzinfo=utc), editable=False),
        ),
    ]
